const $=id=>document.getElementById(id),units={H:'m',T:'s',wind:'m/s',gust:'m/s',current:'m/s',speed:'m/s',L:'m',pto:'N·s/m',diameter:'m',cd:'×',airCd:''};
let params={...defaults},run,frameIndex=0,playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,dirty=false,custom=false,last=performance.now();
const presets=[{label:'Stress test · flat calm',H:0,T:6,wind:0,gust:0,kind:'stress'},...OBS.presets,{label:'Stress test · extreme storm, Hs 16 m',H:16,T:18,wind:45,gust:60,kind:'stress'}];
$('preset').innerHTML=presets.map((p,i)=>`<option value="${i}">${p.label} · ${p.H} m</option>`).join('');$('preset').value='4';$('record-count').textContent=OBS.validRows.toLocaleString();
const keys={
 whole:['Surface hull / waterplane','Navigation & radio mast','PTO / generator enclosure','Main battery pressure pods','Compliant connection / umbilical','Reaction plate / lower frame','AUV capture funnel','Dock latch & charging contacts','Forward wave-driven foil','Aft wave-driven foil','Electric trim thruster','Docked AUV'],
 power:['Surface float / waterplane','PTO cable or sliding rod','Guide and service loop','Bidirectional PTO drum','Generator rotor & stator','Rectifier and DC converter','Battery / charging bus','Compliant connection spring','Submerged reaction plate','Depth-varying wave orbit'],
 underwater:['Pressure pod — battery port','Pressure pod — battery starboard','Reaction plate / structural frame','Compliant connection joint','Dock capture funnel','Vehicle guides & capture latches','Charger / power electronics','AUV body & charging interface','Forward hinged propulsion foil','Aft hinged propulsion foil','Foil actuator / pivot','Electric trim thruster','Acoustic docking beacon'],
 surface:['Surface hull / waterplane','Deckhouse / autonomy computer','Satellite / GNSS / navigation mast','PTO guide and moving rod','PTO drum / bearing supports','Generator / shaft coupling','Rectifier / DC power converter','Auxiliary battery (concept allowance)','Access hatch / seal','Electrical umbilical strain relief','Hull rub rail / spray edge','Wind-exposed superstructure']};
$('key').innerHTML=keys[VIEW].map((s,i)=>`<li><b>${i+1}</b>${s}</li>`).join('');
const explanations={whole:'Shared system response: wave input drives coupled motion, with captured mechanical energy split between generation and foil propulsion. The battery supplies electronics, requested dock charging and estimated thrust assistance. Ground speed is imposed; the model estimates the force and power deficit needed to sustain it rather than claiming an achieved speed.',power:'Changing deployed length alters wave attenuation, spring stiffness and connection drag. The length sweep holds the sea state and all other inputs fixed. The rigid-lock case nearly removes relative heave, demonstrating why a fixed pillar cannot drive this PTO. Peak connection force includes dynamic spring and damper forces, but not static weight/preload.',underwater:'The lower assembly includes the main battery pressure pods, dock, reaction plate, hinged fins and trim thruster. Depth changes orbital flow, drag, pressure and heave. Charging is gated by survival state, a simplified lower-body vertical-speed threshold, and battery reserve; it is not a docking-success model.',surface:'The upper hull experiences aerodynamic load on the exposed structure, hydrodynamic hull drag and vertical wave excitation. Generator, controls and a small auxiliary battery sit on the upper body; the main battery remains in underwater pods. Wind and gust forces are shown separately from wave-driven motion.'};$('explanation').textContent=explanations[VIEW];
function applyPreset(){const q=presets[+$('preset').value];Object.assign(params,{H:q.H,T:q.T,wind:q.wind,gust:q.gust??q.wind});custom=false;sync();recompute();}
function sync(){for(const k in units){$(k).value=params[k];$(k+'-out').textContent=`${Number(params[k]).toFixed(k==='pto'||k==='L'?0:2)} ${units[k]}`;}}
for(const k in units)$(k).addEventListener('input',()=>{params[k]=+$(k).value;if(['H','T','wind','gust'].includes(k))custom=true;sync();dirty=true;});
$('joint').onchange=()=>{params.rigid=$('joint').value==='rigid';dirty=true;};$('charge').onchange=()=>{params.charge=$('charge').value==='true';dirty=true;};$('preset').onchange=applyPreset;
$('play').onclick=()=>{if(frameIndex>=run.points.length-1)frameIndex=0;playing=!playing;$('play').textContent=playing?'Pause':'Play';};
$('time').oninput=()=>{frameIndex=Math.min(run.points.length-1,Math.round(+$('time').value/.2));playing=false;$('play').textContent='Play';render();};
$('download').onclick=()=>{const data={view:VIEW,environmentSource:custom?'User modified observed preset':presets[+$('preset').value],sourceArchive:OBS.url,sourceSha256:OBS.sha256,parameters:params,summary:{averageW:run.avgPower,strokeM:run.stroke,peakDynamicForceN:run.peakForce,energyResidualWh:run.residual,warnings:run.warnings},points:run.points};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`cove-s-${VIEW}-run.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
let timer;document.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>{if(dirty)recompute();},180);});
function metric(label,value,unit){return `<div class="metric"><span>${label}</span><b>${value} <small>${unit}</small></b></div>`;}
function recompute(){dirty=false;run=simulate(params);frameIndex=0;
 const q=presets[+$('preset').value];$('provenance').textContent=(custom?'CUSTOM: environmental values modified. ':q.kind==='observed'?`NOAA 46005 · ${q.time} · `:'SYNTHETIC STRESS TEST · ')+(q.kind==='observed'&&!custom?'Measured Hs, peak period, mean wind and gust. ':'Not a measured sea state. ')+'Current and hardware response assumed.';
 const m={whole:[['Model generation',run.avgPower.toFixed(0),'W'],['Average demand',run.avgLoad.toFixed(0),'W'],['Battery after 3 min',(run.battery/600).toFixed(2),'%'],['Travel required', (params.speed*180).toFixed(0),'m']],power:[['Model generation',run.avgPower.toFixed(0),'W'],['Relative stroke',run.stroke.toFixed(2),'m'],['Peak dynamic load',(run.peakForce/1000).toFixed(1),'kN'],['Mean connection drag',run.beamDrag.toFixed(0),'N']],underwater:[['Absolute pressure',run.pressure.toFixed(2),'bar'],['Lower heave RMS',run.underRms.toFixed(2),'m'],['Mean lower drag',(run.points.reduce((s,p)=>s+p.waterUnder,0)/run.points.length).toFixed(0),'N'],['Battery after 3 min',(run.battery/600).toFixed(2),'%']],surface:[['Upper heave RMS',run.surfaceRms.toFixed(2),'m'],['Mean air load',run.windDrag.toFixed(0),'N'],['Gust air load',run.points[0].gustForce.toFixed(0),'N'],['Model generation',run.avgPower.toFixed(0),'W']]};$('metrics').innerHTML=m[VIEW].map(x=>metric(...x)).join('');
 $('warnings').textContent=run.warnings.length?run.warnings.join(' '):'Within the assumed stroke/load screen for this run. Hardware coefficients remain unvalidated; this is not a safety approval.';
 makeCharts();render();}
const colors={sea:'#59c8e9',power:'#ffc66b',green:'#86e1b2',muted:'#b0c5ce',ink:'#e8f1f4',line:'#29424f',hull:'#cc7837',pod:'#32778b',dark:'#102530'};
function canvas(id){const el=$(id),w=el.clientWidth,h=el.clientHeight,dpr=window.devicePixelRatio||1;if(el.width!==Math.round(w*dpr)||el.height!==Math.round(h*dpr)){el.width=Math.round(w*dpr);el.height=Math.round(h*dpr);}const c=el.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);return {c,w,h};}
function drawDiagram(s){const {c,w,h}=canvas('diagram'),sx=w/640,sy=h/460;const X=x=>x*sx,Y=y=>y*sy;let coords=[];
 const line=(x,y,x2,y2,color=colors.muted,width=2)=>{c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.moveTo(X(x),Y(y));c.lineTo(X(x2),Y(y2));c.stroke();};
 const box=(x,y,ww,hh,color=colors.dark)=>{c.fillStyle=color;c.strokeStyle=colors.muted;c.lineWidth=1;c.beginPath();c.roundRect(X(x),Y(y),ww*sx,hh*sy,5);c.fill();c.stroke();};
 const ellipse=(x,y,rx,ry,col)=>{c.fillStyle=col;c.beginPath();c.ellipse(X(x),Y(y),rx*sx,ry*sy,0,0,7);c.fill();};
 const text=(str,x,y,col=colors.muted)=>{c.fillStyle=col;c.font='12px system-ui';c.fillText(str,X(x),Y(y));};
 const mark=(n,x,y)=>coords.push([n,x,y]);
 const wave=(y)=>{c.fillStyle='#59c8e90b';c.fillRect(0,Y(y),w,h-Y(y));c.beginPath();for(let x=0;x<=640;x+=4){let yy=y+Math.min(18,params.H*4)*Math.sin(x/60-s.t*2*Math.PI/params.T);x?c.lineTo(X(x),Y(yy)):c.moveTo(X(x),Y(yy));}c.strokeStyle=colors.sea;c.lineWidth=2;c.stroke();};
 const prop=(x,y)=>{ellipse(x,y,17,17,colors.dark);for(let j=0;j<3;j++){let a=s.t*3+j*Math.PI*2/3;line(x,y,x+15*Math.cos(a),y+15*Math.sin(a),colors.muted);} };
 const hull=(x,y,ww)=>{c.fillStyle=colors.hull;c.beginPath();c.moveTo(X(x),Y(y));c.lineTo(X(x+ww),Y(y));c.lineTo(X(x+ww-25),Y(y+36));c.lineTo(X(x+25),Y(y+36));c.closePath();c.fill();};
 const fin=(x,y)=>{const d=Math.max(-18,Math.min(18,s.rv*24));line(x-45,y+d,x+45,y-d,colors.green,6);ellipse(x,y,5,5,colors.ink);};
 if(VIEW==='whole'){
  const top=90-Math.tanh(s.zs)*24,bottom=320-Math.tanh(s.zu)*18;wave(115);hull(200,top,250);box(285,top-32,80,32);line(330,top-32,330,top-65);box(220,top-10,45,25);mark(1,432,top+18);mark(2,342,top-65);mark(3,232,top-10);
  line(300,top+36,300,bottom,colors.power,3);line(313,top+36,326,(top+bottom)/2);line(326,(top+bottom)/2,313,bottom);mark(5,326,(top+bottom)/2);
  box(240,bottom,195,18,colors.pod);box(246,bottom-28,76,25,colors.green);box(328,bottom-28,76,25,colors.green);mark(4,378,bottom-20);mark(6,431,bottom+10);
  box(230,bottom+30,155,30,colors.pod);line(230,bottom+30,208,bottom+18);line(230,bottom+60,208,bottom+74);mark(7,202,bottom+25);mark(8,390,bottom+49);ellipse(300,bottom+44,53,8,colors.power);mark(12,288,bottom+43);fin(258,bottom+86);fin(386,bottom+86);mark(9,242,bottom+94);mark(10,384,bottom+94);prop(434,bottom+46);mark(11,455,bottom+46);
  text(`${params.L} m deployed`,25,240);text(`Relative travel ${s.rel.toFixed(2)} m`,25,264);
 }else if(VIEW==='power'){
  const top=90-Math.tanh(s.zs)*22,bottom=350-Math.tanh(s.zu)*15;wave(118);hull(100,top,250);mark(1,115,top+20);
  box(211,top-34,28,66);line(225,top+25,225,bottom,colors.power,3);mark(2,214,top+63);mark(3,253,top-18);
  ellipse(290,top-10,24,24,colors.dark);const a=s.rel*4;line(290-20*Math.cos(a),top-10-20*Math.sin(a),290+20*Math.cos(a),top-10+20*Math.sin(a),colors.power);mark(4,290,top-39);
  box(335,top-26,54,35,colors.pod);mark(5,364,top-43);line(315,top-10,335,top-10);box(420,100,85,48);mark(6,461,92);box(429,224,68,43,colors.green);mark(7,470,280);line(389,top-10,420,124,colors.power);line(461,148,461,224,colors.power);
  c.beginPath();for(let i=0;i<=16;i++){let x=245+(i%2?10:-10),y=top+80+i*(bottom-top-90)/16;i?c.lineTo(X(x),Y(y)):c.moveTo(X(x),Y(y));}c.strokeStyle=colors.muted;c.stroke();mark(8,260,(top+bottom)/2);
  box(130,bottom,190,25,colors.pod);mark(9,146,bottom+40);ellipse(365,bottom,24*Math.exp(-.1*params.L)+4,12*Math.exp(-.1*params.L)+3,colors.sea);mark(10,391,bottom+19);
  text(`${params.L} m connection`,20,244);text(`PTO ${s.power.toFixed(0)} W`,400,180);text(`Δz ${s.rel.toFixed(2)} m`,20,267);
 }else if(VIEW==='underwater'){
  wave(25);let dy=-Math.tanh(s.zu)*18;box(130,165+dy,340,40,colors.pod);mark(3,470,181+dy);
  box(150,110+dy,145,38,colors.green);box(315,110+dy,135,38,colors.green);mark(1,195,108+dy);mark(2,375,108+dy);line(300,30,300,160+dy,colors.power,3);mark(4,315,71+dy);
  box(140,233+dy,310,55,colors.pod);line(140,233+dy,95,207+dy);line(140,288+dy,95,310+dy);mark(5,86,258+dy);mark(6,260,232+dy);box(398,246+dy,25,30,colors.green);mark(7,436,243+dy);ellipse(270,261+dy,105,15,colors.power);mark(8,270,280+dy);
  fin(205,356+dy);fin(408,356+dy);mark(9,173,365+dy);mark(10,422,365+dy);line(205,329+dy,230,300+dy);mark(11,242,327+dy);prop(500,260+dy);mark(12,528,262+dy);box(90,166+dy,20,28);mark(13,84,157+dy);
  text(`Pressure ${s.pressureBar.toFixed(2)} bar abs`,26,417);text(`Orbital flow ${s.orbDeep.toFixed(2)} m/s`,300,417);
 }else{
  let top=220-Math.tanh(s.zs)*20;wave(top+26);hull(65,top,510);mark(1,90,top+32);box(350,top-110,120,110);mark(2,425,top-94);line(410,top-110,410,top-170);ellipse(410,top-160,10,10,colors.power);mark(3,431,top-168);
  box(170,top-40,26,92);line(183,top+52,183,top+126,colors.power,3);mark(4,160,top+76);
  ellipse(227,top-5,28,28,colors.dark);let a=s.rel*4;line(227-22*Math.cos(a),top-5-22*Math.sin(a),227+22*Math.cos(a),top-5+22*Math.sin(a),colors.power);mark(5,226,top-45);
  box(275,top-22,51,35,colors.pod);line(255,top-5,275,top-5);mark(6,300,top-37);box(361,top-50,44,29,colors.power);mark(7,372,top-12);box(412,top-50,43,29,colors.green);mark(8,445,top-12);
  box(486,top-8,50,10);mark(9,515,top-25);line(337,top,349,top+125,colors.green);mark(10,354,top+120);line(111,top+14,160,top+14,colors.muted,4);mark(11,130,top-15);mark(12,495,top-74);
  line(34,70,180,70,colors.sea);text(`Wind ${params.wind.toFixed(1)} m/s`,35,53);text(`Air load ${s.windForce.toFixed(0)} N`,34,99);text('Deck equipment shown in cutaway',32,430);
 }
 for(const [n,x,y]of coords){const px=Math.max(12,Math.min(w-12,X(x))),py=Math.max(12,Math.min(h-12,Y(y)));c.fillStyle=colors.dark;c.strokeStyle=colors.power;c.lineWidth=1;c.beginPath();c.arc(px,py,10,0,7);c.fill();c.stroke();c.fillStyle=colors.power;c.font='11px system-ui';c.textAlign='center';c.textBaseline='middle';c.fillText(n,px,py);c.textAlign='left';c.textBaseline='alphabetic';}
}
let chartDefs=[];
function makeCharts(){const time=run.points.map(x=>x.t);const series=(key,label,color)=>({values:run.points.map(x=>x[key]),label,color});
 const defs={whole:[['Battery energy','kWh',[{values:run.points.map(x=>x.battery/1000),label:'Main battery',color:colors.green}]],['Electrical balance','W',[series('power','Generation',colors.power),series('load','Demand',colors.sea)]],['Coupled heave','m',[series('zs','Surface',colors.power),series('zu','Submerged',colors.sea)]]],power:[['Relative displacement','m',[series('rel','PTO travel',colors.sea)]],['Dynamic connection load','kN',[{values:run.points.map(x=>x.connection/1000),label:'Spring + PTO',color:colors.power}]],['Power conversion','W',[series('mechanical','Captured mechanical',colors.sea),series('power','Electricity',colors.power),series('foil','Foil allocation',colors.green)]]],underwater:[['Lower body motion','m',[series('zu','Heave',colors.sea)]],['Underwater loads','N',[series('waterUnder','Lower drag',colors.sea),series('beam','Connection drag',colors.power)]],['Dock charging delivered','W',[series('charge','AUV charger',colors.green)]]],surface:[['Wave and hull motion','m',[series('eta','Water surface',colors.sea),series('zs','Hull heave',colors.power)]],['Surface forces','N',[series('windForce','Mean-wind drag',colors.green),series('gustForce','Gust envelope',colors.power),series('waterSurface','Hull water drag',colors.sea)]],['Electrical output','W',[series('power','Generator',colors.power)]]]};
 chartDefs=defs[VIEW].map(([title,unit,lines])=>({title,unit,lines,x:time,xlabel:'Time (s)'}));
 if(VIEW==='power'){const lengths=[3,5,8,12,16,20,25,30,40,50],sweep=lengths.map(L=>simulate({...params,L,seconds:60}));chartDefs.push({title:'Length comparison · 60 s screening',unit:'W',x:lengths,xlabel:'Deployed length (m)',lines:[{values:sweep.map(r=>r.avgPower),label:'Mean electric output',color:colors.power}],noGuide:true});}
 $('charts').innerHTML=chartDefs.map((d,i)=>`<div class="panel"><h2>${d.title}</h2><canvas id="chart-${i}" class="chart" role="img" aria-label="${d.title}, ${d.unit}, versus ${d.xlabel}"></canvas></div>`).join('');
}
function drawCharts(){chartDefs.forEach((d,i)=>{const {c,w,h}=canvas(`chart-${i}`),left=57,right=16,top=40,bottom=35,pw=w-left-right,ph=h-top-bottom;const vals=d.lines.flatMap(s=>s.values);let lo=Math.min(...vals),hi=Math.max(...vals);if(hi-lo<1e-7){lo-=1;hi+=1;}const pad=(hi-lo)*.08;lo-=pad;hi+=pad;const X=x=>left+(x-d.x[0])/(d.x.at(-1)-d.x[0])*pw,Y=y=>top+(hi-y)/(hi-lo)*ph;
 c.font='11px system-ui';c.textAlign='left';d.lines.forEach((s,j)=>{c.fillStyle=s.color;c.fillText(s.label,10+(j%2)*w/2,12+Math.floor(j/2)*14);});
 c.strokeStyle=colors.line;c.strokeRect(left,top,pw,ph);for(let j=0;j<4;j++){let v=lo+(hi-lo)*j/3,y=Y(v);c.strokeStyle=colors.line;c.beginPath();c.moveTo(left,y);c.lineTo(w-right,y);c.stroke();c.fillStyle=colors.muted;c.textAlign='right';c.fillText(Math.abs(v)>=1000?(v/1000).toFixed(1)+'k':v.toFixed(1),left-5,y+4);}
 for(let j=0;j<4;j++){let x=d.x[0]+(d.x.at(-1)-d.x[0])*j/3;c.fillStyle=colors.muted;c.textAlign='center';c.fillText(x.toFixed(0),X(x),h-20);}c.fillText(d.xlabel,left+pw/2,h-3);c.textAlign='left';c.fillText(d.unit,2,top-3);
 c.save();c.beginPath();c.rect(left,top,pw,ph);c.clip();for(const s of d.lines){c.beginPath();s.values.forEach((v,j)=>{j?c.lineTo(X(d.x[j]),Y(v)):c.moveTo(X(d.x[j]),Y(v));});c.strokeStyle=s.color;c.lineWidth=1.5;c.stroke();}if(!d.noGuide){c.strokeStyle=colors.muted;c.beginPath();c.moveTo(X(run.points[frameIndex].t),top);c.lineTo(X(run.points[frameIndex].t),top+ph);c.stroke();}c.restore();});}
function render(){const s=run.points[frameIndex];$('clock').textContent=s.t.toFixed(1)+' s';$('time').value=s.t;drawDiagram(s);drawCharts();}
applyPreset();$('play').textContent=playing?'Pause':'Play';
new ResizeObserver(()=>render()).observe($('diagram'));
function tick(now){if(dirty&&now-last>180)recompute();if(playing&&now-last>100){frameIndex=Math.min(frameIndex+1,run.points.length-1);if(frameIndex===run.points.length-1){playing=false;$('play').textContent='Replay';}render();last=now;}requestAnimationFrame(tick);}requestAnimationFrame(tick);
